[theme]
primaryColor = "#3D68EC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
